package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

// initConfigTemplate is the starter config rendered by `daymug init` and
// `daymug bootstrap`. Produces a file that passes config.Validate() out of
// the box: required fields (users.default_home_root absolute path) are
// present, and the rest mirrors
// config.example.yaml so operators have a readable starting point. The
// single %s slot is the absolute users home root. Render via
// renderInitConfig.
//
// SQLite path and config path are NOT in the template — both are
// hard-coded relative to the running binary, see config.DefaultDBPath()
// and config.DefaultConfigFilename.
const initConfigTemplate = `# daymug configuration generated by 'daymug init' / 'daymug bootstrap'.
# Review the values below before running 'daymug serve'.

server:
  # Listen address. Use 127.0.0.1:<port> when fronted by a reverse proxy.
  addr: "127.0.0.1:8090"

auth:
  # How long a successful login stays valid (Go duration syntax).
  session_ttl: 720h
  # Force the Secure flag on the session cookie. Left false the flag is still
  # set automatically for requests that arrived over HTTPS (direct TLS or a
  # proxy forwarding X-Forwarded-Proto); set true only when TLS is terminated
  # by a proxy that does not forward that header.
  cookie_secure: false
  # Username + password login. Disable when only OIDC should grant access.
  password_login_enabled: true

admin:
  # Usernames in this list are auto-promoted to is_admin=true on every restart.
  # Recovery hatch: drop your username here, restart, you're admin again.
  bootstrap_usernames:
    - admin

users:
  # New human users default to <default_home_root>/<username> as their work
  # directory. Must be an absolute path; resolved at install/init time.
  default_home_root: %s
  # Tasks one user may run at once across all accounts and entry points
  # (web, API, IM, /compact). Extra tasks queue. Default 4.
  max_concurrent: 4

# Provider accounts, credentials, model lists, and pricing are configured in
# Admin settings -> Providers & models and stored in SQLite.

# Per-process isolation around each agent invocation. "noop" is a
# pass-through: the agent has the same filesystem reach as the server user.
# On Linux, type: bwrap confines each agent to its own work_dir instead;
# see config.example.yaml for the bind/network knobs it adds.
sandbox:
  enabled: false
  type: noop

# Optional OIDC single sign-on (Casdoor / generic). Disabled by default.
oidc:
  enabled: false

# Self-upgrade settings. Manifest URL is hard-coded server-side; only the
# service-runtime knobs live here.
upgrade:
  service: daymug
  service_mode: user
  health_path: "/api/health"
  health_timeout: 60s
`

func cmdInit() {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	force := fs.Bool("force", false, "Overwrite an existing config.yaml")
	if err := fs.Parse(os.Args[2:]); err != nil {
		fatalf("parse args: %v", err)
	}

	cwd, err := os.Getwd()
	if err != nil {
		fatalf("get working directory: %v", err)
	}

	target, homeRoot, dataDir, err := runInit(cwd, *force)
	if err != nil {
		fatalf("%v", err)
	}

	fmt.Printf("Wrote %s\n", target)
	fmt.Printf("  database (auto):         %s\n", filepath.Join(dataDir, "database.db"))
	fmt.Printf("  users.default_home_root: %s\n", homeRoot)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Review config.yaml — set admin.bootstrap_usernames and any providers")
	fmt.Println("     credentials directories / API keys you want to use.")
	fmt.Println("  2. Make sure the `claude` CLI is installed and authenticated (`claude /login`).")
	fmt.Println("  3. Run `daymug serve` from this directory, or `daymug bootstrap` to lay")
	fmt.Println("     out the canonical ~/.daymug/ layout and register a user-level service.")
}

// runInit performs the side effects of `daymug init` against the given
// directory: writes config.yaml, mkdirs data/ and users/. Returns the absolute
// paths of (config, users, data) so the caller can show them in the success
// message. Split out so tests can drive it with a temp dir without touching
// process-global state.
func runInit(cwd string, force bool) (configPath, homeRoot, dataDir string, err error) {
	configPath = filepath.Join(cwd, "config.yaml")
	if _, statErr := os.Stat(configPath); statErr == nil && !force {
		return "", "", "", fmt.Errorf("refusing to overwrite %s (pass --force to replace)", configPath)
	}

	homeRoot = filepath.Join(cwd, "users")
	dataDir = filepath.Join(cwd, "data")

	if mkErr := os.MkdirAll(dataDir, 0o755); mkErr != nil {
		return "", "", "", fmt.Errorf("create %s: %w", dataDir, mkErr)
	}
	if mkErr := os.MkdirAll(homeRoot, 0o755); mkErr != nil {
		return "", "", "", fmt.Errorf("create %s: %w", homeRoot, mkErr)
	}

	if writeErr := os.WriteFile(configPath, []byte(renderInitConfig(homeRoot)), 0o644); writeErr != nil {
		return "", "", "", fmt.Errorf("write %s: %w", configPath, writeErr)
	}
	return configPath, homeRoot, dataDir, nil
}

// renderInitConfig fills initConfigTemplate with the supplied homeRoot.
// Pulled out so the install path and init path render the same way.
func renderInitConfig(homeRoot string) string {
	return fmt.Sprintf(initConfigTemplate, homeRoot)
}
