// Package store_test hosts the cross-layer API contract snapshot.
//
// The frontend's request/response types are hand-written and there is no
// codegen keeping them honest, so changing a Go struct's json tags used to be
// a silent break: the backend ships a renamed field, the SPA keeps reading the
// old one, and nothing fails until someone clicks the right button. Codegen
// was evaluated and rejected — most handlers return anonymous gin.H maps, so
// there is very little to generate from, and generated types would flatten the
// literal unions and derived types the frontend deliberately hand-writes.
//
// This snapshot buys the main benefit instead: it pins the JSON field names
// and optionality of the types the SPA actually models. Adding, removing, or
// renaming a field fails this test, which forces the change to be paired with
// a frontend update (or a deliberate exemption). frontend/scripts/
// check-api-contract.mjs reads the same golden file from the other side.
//
// It lives in package store_test (external) so it can import internal/service
// without an import cycle.
package store_test

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"
	"time"

	"github.com/DayMug/DayMug/backend/internal/service"
	"github.com/DayMug/DayMug/backend/internal/store"
)

var updateContract = flag.Bool("update-contract", false, "rewrite contract.golden.json from the current Go types")

const contractGoldenPath = "contract.golden.json"

// contractType records one Go type in the snapshot plus where the frontend
// models it. The TS coordinates are not used by this test — they tell
// check-api-contract.mjs which interface to compare against, and they tell a
// human reading a failure which file to go fix.
type contractType struct {
	// Sample is a value of the Go type. It is passed through encoding/json
	// rather than reflected over, so types with a custom MarshalJSON are
	// captured as they actually appear on the wire.
	Sample any

	TSInterface string
	TSFile      string
}

// contractTypes is the whitelist. It is deliberately small: these are the
// stable, long-lived payloads the SPA models as named interfaces. Growing it
// is welcome; every entry needs a matching TS interface.
var contractTypes = map[string]contractType{
	"service.ServerMessage": {
		Sample:      service.ServerMessage{},
		TSInterface: "WSMessage",
		TSFile:      "src/lib/wsProtocol.ts",
	},
	"store.Conversation": {
		Sample:      store.Conversation{},
		TSInterface: "Conversation",
		TSFile:      "src/composables/types/chat.ts",
	},
	"store.ConversationAttention": {
		Sample:      store.ConversationAttention{},
		TSInterface: "ConversationAttentionRow",
		TSFile:      "src/composables/types/chat.ts",
	},
	"store.User": {
		Sample:      store.User{},
		TSInterface: "User",
		TSFile:      "src/composables/types/user.ts",
	},
	"store.CronJob": {
		Sample:      store.CronJob{},
		TSInterface: "CronJob",
		TSFile:      "src/composables/types/cron.ts",
	},
	"store.UsageInsightsResponse": {
		Sample:      store.UsageInsightsResponse{},
		TSInterface: "UsageInsightsResponse",
		TSFile:      "src/composables/types/admin.ts",
	},
	"store.MarketplaceApp": {
		Sample:      store.MarketplaceApp{},
		TSInterface: "MarketplaceApp",
		TSFile:      "src/composables/apiMarketplace.ts",
	},
	// store.Message has a custom MarshalJSON that retypes Content to `any`
	// and drops SourceID, so reflecting over its struct tags would describe a
	// shape the wire never carries. Going through json.Marshal is what makes
	// this entry correct.
	"store.Message": {
		Sample:      store.Message{},
		TSInterface: "ChatMessage",
		TSFile:      "src/composables/types/chat.ts",
	},
}

// contractSnapshot is the on-disk format. Field lists are sorted so the golden
// file diffs cleanly.
type contractSnapshot struct {
	Note  string                    `json:"_note"`
	Types map[string]contractFields `json:"types"`
}

type contractFields struct {
	TSInterface    string   `json:"ts_interface"`
	TSFile         string   `json:"ts_file"`
	RequiredFields []string `json:"required_fields"`
	OptionalFields []string `json:"optional_fields"`
}

const snapshotNote = "Generated by `go test ./internal/store -run TestAPIContractSnapshot -update-contract`. " +
	"Field names + optionality only, never types — the frontend deliberately narrows some fields " +
	"(literal unions, Pick<> derivations) and comparing types would fight that."

// TestAPIContractSnapshot pins the wire shape of every whitelisted type.
func TestAPIContractSnapshot(t *testing.T) {
	t.Parallel()
	got := contractSnapshot{Note: snapshotNote, Types: map[string]contractFields{}}
	for name, ct := range contractTypes {
		required, optional, err := wireFields(ct.Sample)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		got.Types[name] = contractFields{
			TSInterface:    ct.TSInterface,
			TSFile:         ct.TSFile,
			RequiredFields: required,
			OptionalFields: optional,
		}
	}

	encoded, err := json.MarshalIndent(got, "", "  ")
	if err != nil {
		t.Fatalf("marshal snapshot: %v", err)
	}
	encoded = append(encoded, '\n')

	path := filepath.Join(".", contractGoldenPath)
	if *updateContract {
		if err := os.WriteFile(path, encoded, 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("wrote %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden (run with -update-contract to create it): %v", err)
	}
	if bytes.Equal(want, encoded) {
		return
	}

	// Report the diff per type rather than dumping two JSON blobs.
	var prev contractSnapshot
	if err := json.Unmarshal(want, &prev); err != nil {
		t.Fatalf("golden file is not valid JSON: %v", err)
	}
	for name, nowFields := range got.Types {
		wasFields, ok := prev.Types[name]
		if !ok {
			t.Errorf("%s: new type in the contract whitelist", name)
			continue
		}
		reportFieldDiff(t, name+" required", wasFields.RequiredFields, nowFields.RequiredFields)
		reportFieldDiff(t, name+" optional", wasFields.OptionalFields, nowFields.OptionalFields)
	}
	for name := range prev.Types {
		if _, ok := got.Types[name]; !ok {
			t.Errorf("%s: dropped from the contract whitelist", name)
		}
	}
	t.Errorf("API contract changed. If this is intentional, update the matching TypeScript "+
		"interface (see ts_file/ts_interface in %s), then re-run with -update-contract.", contractGoldenPath)
}

func reportFieldDiff(t *testing.T, label string, was, now []string) {
	t.Helper()
	wasSet := map[string]bool{}
	for _, f := range was {
		wasSet[f] = true
	}
	nowSet := map[string]bool{}
	for _, f := range now {
		nowSet[f] = true
	}
	for _, f := range now {
		if !wasSet[f] {
			t.Errorf("%s: field %q added", label, f)
		}
	}
	for _, f := range was {
		if !nowSet[f] {
			t.Errorf("%s: field %q removed", label, f)
		}
	}
}

// wireFields returns the JSON keys a type can emit, split by optionality.
//
// It marshals the type twice — once zero-valued, once with every field set to
// something non-zero — and compares the key sets. A key present in both is
// always emitted (required); a key that only shows up in the populated pass is
// dropped when empty (`omitempty` / `omitzero`, i.e. optional). Doing it
// through encoding/json rather than reflecting over struct tags means custom
// MarshalJSON implementations, embedded structs, and `json:"-"` are all
// honoured for free.
func wireFields(sample any) (required, optional []string, err error) {
	// Non-nil so an empty list serialises as [] rather than null.
	required, optional = []string{}, []string{}
	t := reflect.TypeOf(sample)

	zero := reflect.New(t).Elem()
	full := reflect.New(t).Elem()
	fillNonZero(full)

	zeroKeys, err := marshalKeys(zero.Interface())
	if err != nil {
		return nil, nil, err
	}
	fullKeys, err := marshalKeys(full.Interface())
	if err != nil {
		return nil, nil, err
	}

	for key := range fullKeys {
		if zeroKeys[key] {
			required = append(required, key)
		} else {
			optional = append(optional, key)
		}
	}
	// A key that only appears when zero-valued would mean a marshaler that
	// branches on content. None exist today; surface it rather than hide it.
	for key := range zeroKeys {
		if !fullKeys[key] {
			return nil, nil, errUnstableKey(key)
		}
	}

	sort.Strings(required)
	sort.Strings(optional)
	return required, optional, nil
}

type errUnstableKey string

func (e errUnstableKey) Error() string {
	return "field " + string(e) + " is emitted only for the zero value; the contract snapshot cannot describe it"
}

func marshalKeys(v any) (map[string]bool, error) {
	raw, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(raw, &obj); err != nil {
		return nil, err
	}
	keys := make(map[string]bool, len(obj))
	for k := range obj {
		keys[k] = true
	}
	return keys, nil
}

var (
	timeType       = reflect.TypeOf(time.Time{})
	rawMessageType = reflect.TypeOf(json.RawMessage{})
)

// fillNonZero recursively sets v to a non-zero value so that `omitempty`
// fields survive marshalling. Values are arbitrary — only presence matters.
func fillNonZero(v reflect.Value) {
	switch v.Type() {
	case timeType:
		v.Set(reflect.ValueOf(time.Unix(1, 0).UTC()))
		return
	case rawMessageType:
		// Must stay valid JSON or json.Marshal fails on the whole struct.
		v.Set(reflect.ValueOf(json.RawMessage(`{"contract":true}`)))
		return
	}

	switch v.Kind() {
	case reflect.Pointer:
		v.Set(reflect.New(v.Type().Elem()))
		fillNonZero(v.Elem())
	case reflect.Struct:
		for i := range v.NumField() {
			if v.Type().Field(i).IsExported() {
				fillNonZero(v.Field(i))
			}
		}
	case reflect.Slice:
		v.Set(reflect.MakeSlice(v.Type(), 1, 1))
		fillNonZero(v.Index(0))
	case reflect.Map:
		v.Set(reflect.MakeMap(v.Type()))
		key := reflect.New(v.Type().Key()).Elem()
		fillNonZero(key)
		val := reflect.New(v.Type().Elem()).Elem()
		fillNonZero(val)
		v.SetMapIndex(key, val)
	case reflect.Interface:
		// `any` fields (ServerMessage.Content) just need to be non-nil.
		v.Set(reflect.ValueOf("contract"))
	case reflect.String:
		v.SetString("contract")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	}
}
